### PR TITLE
add wegithed least squares approach

### PR DESCRIPTION
**Pull request by cjekel**
@vkhodygo Can your review this and let me know if it address your desire in https://github.com/cjekel/piecewise_linear_fit_py/pull/60 ?

This approach uses this math:
image

[Example](https://github.com/cjekel/piecewise_linear_fit_py/blob/weights/examples/weighted_least_squares_ex.py) of difference between ordinary pwlf and this weighted least squares fit
image

What is needed to merge into master
- [x] ~~make work with constrained least squares (x_c y_c)~~ abandoned because of ill conditioning
- [ ] add tests
- [x] add written example to examples.md
- [x] ~~ include weights in standard_errors? (not sure about this Feb 11, 2020)~~ Prediction variance with weights doesn't make any sense... but I added weights to standard errors.

### CODE REVIEW

**Comment by cjekel** [comment]
I corrected the weighted sum-of-square of residuals in this equation
image

**Comment by vkhodygo** [comment]
Hi, @cjekel 

Yes, this is exactly what I wanted. I should probably close my initial PR as it is redundant.

**Comment by cjekel** [comment]
@vkhodygo Not sure when I'll get to finishing this.

The biggest things will be getting constrained least squares to work and getting standard errors to work.

If you want to take a stab at finishing this PR, feel free to go ahead! :) I have no hard deadline for merging this.

**Comment by cjekel** [comment]
- [ ] Consider allowing the user to manually specify the weight matrix from Tyler @ UT Austin

**Pull request merged**
